import Head from 'next/head';
import { Button } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Button>سلام!</Button>
    </>
  );
}
