import Head from 'next/head';

// *
import ListIp from '@/components/list/ListIp';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ListIp />
    </>
  );
}
